channels:
- conda-forge
dependencies:
- python=3.8.10
- pip<=25.0.1
- pip:
  - mlflow==2.17.2
  - numpy==1.24.4
  - pandas==2.0.3
  - psutil==7.0.0
  - scikit-learn==1.3.2
  - scipy==1.10.1
  - xgboost==2.1.4
name: mlflow-env
