name: Run Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Change si nécessaire

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Assure-toi que pytest est listé ici

      - name: Install pytest
        run: pip install pytest  # Ajouté pour éviter l'erreur

      - name: Run tests
        run: pytest tests/

